# Generated by Django 4.1.3 on 2022-11-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSerializer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=9999999)),
                ('url', models.CharField(max_length=9999999)),
                ('content_html', models.CharField(max_length=9999999)),
                ('summary', models.CharField(max_length=9999999)),
                ('date_published', models.CharField(max_length=9999999)),
                ('image', models.CharField(max_length=9999999)),
                ('author', models.CharField(max_length=9999999)),
            ],
        ),
    ]
