# Generated by Django 4.1.3 on 2022-11-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_tag_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date_modified',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
