# Generated by Django 4.1.3 on 2022-11-27 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_attachment_url_alter_attachment_duration_in_seconds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='news',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.news'),
        ),
    ]
